"""Generate the PyInstaller spec file for Android TV Desktop Toolkit.

Called from scripts/build.ps1. Tcl/Tk runtime files are handled automatically
by PyInstaller's built-in hook-_tkinter.py — we do NOT add them manually.
"""
import sys
import os

def generate_spec(root: str) -> str:
    py_file = os.path.join(root, 'android_tv_tools.py')

    # CustomTkinter path
    import customtkinter
    ctk_dir = os.path.dirname(customtkinter.__file__)

    all_datas = [
        (os.path.join(root, 'assets'), 'assets'),
        (ctk_dir, 'customtkinter'),
    ]

    datas_lines = ['[\n']
    for src, dest in all_datas:
        datas_lines.append(f"    ({repr(src)}, {repr(dest)}),\n")
    datas_lines.append(']')
    datas_repr = ''.join(datas_lines)

    icon_path = os.path.join(root, 'assets', 'icon.ico')

    spec = f'''# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by scripts/generate_spec.py — do not edit by hand.
a = Analysis(
    [{repr(py_file)}],
    pathex=[],
    binaries=[],
    datas={datas_repr},
    hiddenimports=[],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Android TV Desktop Toolkit',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=[{repr(icon_path)}],
)
'''
    spec_path = os.path.join(root, 'Android TV Desktop Toolkit.spec')
    with open(spec_path, 'w') as f:
        f.write(spec)
    print(f'Spec written: {spec_path}')
    print(f'App data files: {len(all_datas)} (assets + customtkinter)')
    return spec_path


if __name__ == '__main__':
    # Root is passed as argv[1] or defaults to parent of this script's dir
    if len(sys.argv) > 1:
        root = sys.argv[1]
    else:
        root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    generate_spec(root)
